name: Trigger Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/SMART-NYUAD/deploy/dispatches \
            -d '{"event_type":"deploy"}'